name: "🔥 Bug report"
description: Create a report to help us improve
labels: ["status: needs testing", "type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Before You Start:**

        This form is for submitting bug reports. If you have a usage question
        or are unsure if this is really a bug, make sure to:

        - Ask on our [Discord Chat](https://discord.com/invite/Nt467Rf/)

        Also try to search for your issue - it may have already been answered or even fixed in a development branch.
        However, if you find that an old, closed issue still persists in the latest version,
        you should open a new issue using the form below instead of commenting on the old issue.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        What do we need to do in order to make the bug happen? Clear and concise reproduction instructions are important for us to be able to triage your issue in a timely manner. 
      placeholder: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is expected?
    validations:
      required: true
  - type: textarea
    id: actually-happening
    attributes:
      label: What is actually happening?
    validations:
      required: true
  - type: textarea
    id: server-info
    attributes:
      label: Server Info
      description: "- Minecraft version: [e.g. 1.18.2]
                    - Server version [e.g. Spigot, Paper]
                    - Plugin version [e.g. 2.17.1]"
      render: shell
      placeholder: "- Minecraft version: [e.g. 1.18.2]
                    - Server version [e.g. Spigot, Paper]
                    - Plugin version [e.g. 2.17.1]"
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
      description: For example some background / context of how you ran into this bug.
